language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

matrix:
    fast_finish: true

before_script:
    - composer self-update
    - composer install

script:
    - make lint
    - make test

after_script:
    - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
